-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 13:29:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema decathlon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema decathlon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decathlon` DEFAULT CHARACTER SET utf8 ;
USE `decathlon` ;

-- -----------------------------------------------------
-- Table `decathlon`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decathlon`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decathlon`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decathlon`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_categoria` INT NOT NULL,
  `nombre` VARCHAR(75) NOT NULL,
  `talla` VARCHAR(15) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `fk_categoria`),
  INDEX `fk_Producto_Categoria_idx` (`fk_categoria` ASC) ,
  CONSTRAINT `fk_Producto_Categoria`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `decathlon`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
